export enum ErrorMessageEnum {
    ERROR = 'ERROR',
    MISSING_PARAMETERS = 'MISSING_PARAMETERS',
    AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
    TOO_MANY_REQUEST = 'TOO_MANY_REQUEST',
    NOT_FOUND = 'NOT_FOUND',
    FORBIDDEN = 'FORBIDDEN',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
}
